name: Version taggin

on:
  push:
    branches:
      - master

jobs:
  version_tagging_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
